package net.berinle.hibsearch.model;

public enum Country {
	
	AFGHANISTAN ("Afghanistan"),
	ALBANIA ("Albania"),
	ALGERIA ("Algeria"),
	AMERICAN_SAMOA ("American Samoa"),
	ANDORRA ("Andorra"),
	ANGOLA ("Angola"),
	ANGUILLA ("Anguilla"),
	ANTARCTICA ("Antarctica"),
	ANTIGUA_AND_BARBUDA ("Antigua & Barbuda"),
	ARGENTINA ("Argentina"),
	ARMENIA ("Armenia"),
	ARUBA ("Aruba"),
	AUSTRALIA ("Australia"),
	AUSTRIA ("Austria"),
	AZERBAIJAN ("Azerbaijan"),
	BAHAMAS ("Bahamas"),
	BAHRAIN ("Bahrain"),
	BANGLADESH ("Bangladesh"),
	BARBADOS ("Barbados"),
	BELARUS ("Belarus"),
	BELGIUM ("Belgium"),
	BELIZE ("Belize"),
	BENIN ("Benin"),
	BERMUDA ("Bermuda"),
	BHUTAN ("Bhutan"),
	BOLIVIA ("Bolivia"),
	BOSNIA_AND_HERZEG ("Bosnia & Herzeg..."),
	BOTSWANA ("Botswana"),
	BOUVET_ISLAND ("Bouvet Island"),
	BRAZIL ("Brazil"),
	BRITISH_INDIAN_OCEAN ("British Indian Ocean"),
	BRUNEI_DARUSSALAM ("Brunei Darussalam"),
	BULGARIA ("Bulgaria"),
	BURKINA_FASO ("Burkina Faso"),
	BURUNDI ("Burundi"),
	CAMBODIA ("Cambodia"),
	CAMEROON ("Cameroon"),
	CANADA ("Canada"),
	CAPE_VERDE ("Cape Verde"),
	CAYMAN_ISLANDS ("Cayman Islands"),
	CENTRAL_AFRICAN_REP ("Central African Rep."),
	CHAD ("Chad"),
	CHILE ("Chile"),
	CHINA ("China"),
	CHRISTMAS_ISLAND ("Christmas Island"),
	COCOS_KEELING_ISL ("Cocos (Keeling) Isl."),
	COLOMBIA ("Colombia"),
	COMOROS ("Comoros"),
	CONGO ("Congo"),
	COOK_ISLANDS ("Cook Islands"),
	COSTA_RICA ("Costa Rica"),
	COTE_DIVOIRE ("Cote D'Ivoire"),
	CROATIA_HRVATSKA ("Croatia (Hrvatska)"),
	CUBA ("Cuba"),
	CYPRUS ("Cyprus"),
	CZECH_REPUBLIC ("Czech Republic"),
	DENMARK ("Denmark"),
	DJIBOUTI ("Djibouti"),
	DOMINICA ("Dominica"),
	DOMINICAN_REP ("Dominican Rep."),
	EAST_TIMOR ("East Timor"),
	ECUADOR ("Ecuador"),
	EGYPT ("Egypt"),
	EL_SALVADOR ("El Salvador"),
	EQUATORIAL_GUINEA ("Equatorial Guinea"),
	ERITREA ("Eritrea"),
	ESTONIA ("Estonia"),
	ETHIOPIA ("Ethiopia"),
	FALKLAND_ISLANDS ("Falkland Islands"),
	FAROE_ISLANDS ("Faroe Islands"),
	FIJI ("Fiji"),
	FINLAND ("Finland"),
	FRANCE ("France"),
	FRANCE_METROPOLITAN ("France, Metropolitan"),
	FRENCH_GUIANA ("French Guiana"),
	FRENCH_POLYNESIA ("French Polynesia"),
	FRENCH_SOUTHERN_TERR ("French Southern terr."),
	GABON ("Gabon"),
	GAMBIA ("Gambia"),
	GEORGIA ("Georgia"),
	GERMANY ("Germany"),
	GHANA ("Ghana"),
	GIBRALTAR ("Gibraltar"),
	GREECE ("Greece"),
	GREENLAND ("Greenland"),
	GRENADA ("Grenada"),
	GUADELOUPE ("Guadeloupe"),
	GUAM ("Guam"),
	GUATEMALA ("Guatemala"),
	GUINEA ("Guinea"),
	GUINEA_BISSAU ("Guinea-Bissau"),
	GUYANA ("Guyana"),
	HAITI ("Haiti"),
	HEARD_AND_MCDONALDS ("Heard & Mc Donalds"),
	HONDURAS ("Honduras"),
	HONG_KONG ("Hong Kong"),
	HUNGARY ("Hungary"),
	ICELAND ("Iceland"),
	INDIA ("India"),
	INDONESIA ("Indonesia"),
	IRAN ("Iran"),
	IRAQ ("Iraq"),
	IRELAND ("Ireland"),
	ISRAEL ("Israel"),
	ITALY ("Italy"),
	JAMAICA ("Jamaica"),
	JAPAN ("Japan"),
	JORDAN ("Jordan"),
	KAZAKHSTAN ("Kazakhstan"),
	KENYA ("Kenya"),
	KIRIBATI ("Kiribati"),
	KOREA ("Korea"),
	KOREA_REPUBLIC_OF ("Korea, Republic of"),
	KUWAIT ("Kuwait"),
	KYRGYZSTAN ("Kyrgyzstan"),
	LAO ("Lao"),
	LATVIA ("Latvia"),
	LEBANON ("Lebanon"),
	LESOTHO ("Lesotho"),
	LIBERIA ("Liberia"),
	LIBYAN_ARAB_JAMAHIRIYA ("Libyan Arab Jamahiriya"),
	LIECHTENSTEIN ("Liechtenstein"),
	LITHUANIA ("Lithuania"),
	LUXEMBOURG ("Luxembourg"),
	MACAU ("Macau"),
	MACEDONIA ("Macedonia"),
	MADAGASCAR ("Madagascar"),
	MALAWI ("Malawi"),
	MALAYSIA ("Malaysia"),
	MALDIVES ("Maldives"),
	MALI ("Mali"),
	MALTA ("Malta"),
	MARSHALL_ISLANDS ("Marshall Islands"),
	MARTINIQUE ("Martinique"),
	MAURITANIA ("Mauritania"),
	MAURITIUS ("Mauritius"),
	MAYOTTE ("Mayotte"),
	MEXICO ("Mexico"),
	MICRONESIA ("Micronesia"),
	MOLDOVA ("Moldova"),
	MONACO ("Monaco"),
	MONGOLIA ("Mongolia"),
	MONTSERRAT ("Montserrat"),
	MOROCCO ("Morocco"),
	MOZAMBIQUE ("Mozambique"),
	MYANMAR ("Myanmar"),
	NAMIBIA ("Namibia"),
	NAURU ("Nauru"),
	NEPAL ("Nepal"),
	NETHERLANDS ("Netherlands"),
	NETHERLANDS_ANTILLES ("Netherlands Antilles"),
	NEW_CALEDONIA ("New Caledonia"),
	NEW_ZEALAND ("New Zealand"),
	NICARAGUA ("Nicaragua"),
	NIGER ("Niger"),
	NIGERIA ("Nigeria"),
	NIUE ("Niue"),
	NORFOLK_ISLAND ("Norfolk Island"),
	NORTHERN_MARIANA_ISLANDS ("Northern Mariana Islands"),
	NORWAY ("Norway"),
	OMAN ("Oman"),
	PAKISTAN ("Pakistan"),
	PALAU ("Palau"),
	PANAMA ("Panama"),
	PAPUA_NEW_GUINEA ("Papua New Guinea"),
	PARAGUAY ("Paraguay"),
	PERU ("Peru"),
	PHILIPPINES ("Philippines"),
	PITCAIRN ("Pitcairn"),
	POLAND ("Poland"),
	PORTUGAL ("Portugal"),
	PUERTO_RICO ("Puerto Rico"),
	QATAR ("Qatar"),
	REUNION ("Reunion"),
	ROMANIA ("Romania"),
	RUSSIAN_FEDERATION ("Russian Federation"),
	RWANDA ("Rwanda"),
	SAINT_KITTS_AND_NEVIS ("Saint Kitts and Nevis"),
	SAINT_LUCIA ("Saint Lucia"),
	SAINT_VINCENT_AND_GRENADINES ("Saint Vincent & Grenadines"),
	SAMOA ("Samoa"),
	SAN_MARINO ("San Marino"),
	SAO_TOME_AND_PRINCIPE ("Sao Tome and Principe"),
	SAUDI_ARABIA ("Saudi Arabia"),
	SENEGAL ("Senegal"),
	SEYCHELLES ("Seychelles"),
	SIERRA_LEONE ("Sierra Leone"),
	SINGAPORE ("Singapore"),
	SLOVAKIA_SLOVAK_REP_ ("Slovakia (Slovak Rep)"),
	SLOVENIA ("Slovenia"),
	SOLOMON_ISLANDS ("Solomon Islands"),
	SOMALIA ("Somalia"),
	SOUTH_AFRICA ("South Africa"),
	SPAIN ("Spain"),
	SRI_LANKA ("Sri Lanka"),
	ST_HELENA ("St. Helena"),
	ST_PIERRE_AND_MIQUELON ("St. Pierre and Miquelon"),
	SUDAN ("Sudan"),
	SURINAME ("Suriname"),
	SVALBARD_JAN_MAYEN ("Svalbard Jan Mayen"),
	SWAZILAND ("Swaziland"),
	SWEDEN ("Sweden"),
	SWITZERLAND ("Switzerland"),
	SYRIAN_ARAB_REPUBLIC ("Syrian Arab Republic"),
	TAIWAN ("Taiwan"),
	TAJIKISTAN ("Tajikistan"),
	TANZANIA ("Tanzania"),
	THAILAND ("Thailand"),
	TOGO ("Togo"),
	TOKELAU ("Tokelau"),
	TONGA ("Tonga"),
	TRINIDAD_AND_TOBAGO ("Trinidad and Tobago"),
	TUNISIA ("Tunisia"),
	TURKEY ("Turkey"),
	TURKMENISTAN ("Turkmenistan"),
	TURKS_AND_CAICOS_ISLANDS ("Turks & Caicos Islands"),
	TUVALU ("Tuvalu"),
	UGANDA ("Uganda"),
	UKRAINE ("Ukraine"),
	UNITED_ARAB_EMIRATES ("United Arab Emirates"),
	UNITED_KINGDOM ("United Kingdom"),
	UNITED_STATES ("United States"),
	UNITED_STATES_MINOR_ISLANDS ("United States Minor Islands"),
	URUGUAY ("Uruguay"),
	UZBEKISTAN ("Uzbekistan"),
	VANUATU ("Vanuatu"),
	VATICAN_CITY_STATE ("Vatican City State"),
	VENEZUELA ("Venezuela"),
	VIET_NAM ("Viet NAM"),
	VIRGIN_ISLANDS_BRITISH ("Virgin Islands (British)"),
	VIRGIN_ISLANDS_US ("Virgin Islands (U.S.)"),
	WALLIS_AND_FUTUNA_ISLANDS ("Wallis & Futuna Islands"),
	WESTERN_SAHARA ("Western Sahara"),
	YEMEN ("Yemen"),
	YUGOSLAVIA ("Yugoslavia"),
	ZAIRE ("Zaire"),
	ZAMBIA ("Zambia"),
	ZIMBABWE ("Zimbabwe");
	
	private String name;
	
	private Country( String name ) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
	
	
}
